name: build-ffmpeg
on:
  push:
  # TODO: add filter so that it only runs on master when something relevant changes

jobs:
  build-windows:
    name: Build FFMpeg Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build FFmpeg
        shell: "bash"
        run: |
          export PATH="$(pwd)/vendor:$PATH"
          echo $PATH
          which yasm

          cd FFmpeg
          ls -la
          pwd

          ./configure --toolchain=msvc \
            --target-os=win64 \
            --arch=x86_64 \
            --disable-debug \
            --enable-stripping \
            --enable-shared \
            --shlibdir=SHARED_LIBS \
            --enable-pic \
            --disable-autodetect \
            --disable-programs \
            --enable-avcodec \
            --disable-avdevice \
            --enable-avfilter \
            --enable-avformat \
            --enable-avutil \
            --enable-postproc \
            --enable-swresample \
            --enable-swscale
          
          echo "Removing link as it might conflict"
          rm -Rf /usr/bin/link

          echo "Compiling"
          make -j4

          echo "Installing"
          make install
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
