name: build-ffmpeg
on:
  push:
  # TODO: add filter so that it only runs on master when something relevant changes

jobs:
  build-windows:
    name: Build FFMpeg Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: msys2/setup-msys2@v2
        with:
          path-type: 'inherit'
      - name: Installing dependencies
        shell: msys2 {0}
        run: |
          pacman -S --noconfirm make
          which make
      - name: Configure FFmpeg
        shell: "bash"
        run: |
          export PATH="$(pwd)/vendor:$PATH"
          echo $PATH
          which yasm

          cd FFmpeg
          ls -la
          pwd

          ./configure --toolchain=msvc \
            --target-os=win64 \
            --arch=x86_64 \
            --disable-debug \
            --enable-stripping \
            --enable-shared \
            --shlibdir=SHARED_LIBS \
            --enable-pic \
            --disable-autodetect \
            --disable-programs \
            --enable-avcodec \
            --disable-avdevice \
            --enable-avfilter \
            --enable-avformat \
            --enable-avutil \
            --enable-postproc \
            --enable-swresample \
            --enable-swscale
      - name: Build FFmpeg
        shell: msys2 {0}
        run: |
          export PATH="$(pwd)/vendor:$PATH"
          echo $PATH
          which yasm

          cd FFmpeg
          ls -la
          pwd

          echo "Removing link as it might conflict"
          rm -Rf /usr/bin/link

          echo "Compiling"
          /usr/bin/make -j8

          echo "Installing"
          /usr/bin/make install
      - name: Package libraries
        run: |
          $sha = git rev-parse HEAD
          $zipName = "${sha}_x86_64-pc-windows-msvc.zip"
          Compress-Archive -Path "FFmpeg/SHARED_LIBS" -DestinationPath $zipName

          # Pass zip name to next step
          echo "::set-output name=zipName::$zipName"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: $zipName
          path: $zipName
      # - name: Setup tmate session
      #   if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3
