name: build-ffmpeg
on:
  push:
  # TODO: add filter so that it only runs on master when something relevant changes

jobs:
  build-windows:
    name: Build FFMpeg Windows
    runs-on: windows-latest
    permissions:
      contents: write
    strategy:
      matrix:
        configuration: ["standard"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      # TODO: check if configuration is already there
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: msys2/setup-msys2@v2
        with:
          path-type: 'inherit'
      - name: Installing dependencies
        shell: msys2 {0}
        run: |
          pacman -S --noconfirm make
          which make
      - name: Preparing configuration
        shell: "bash"
        run: |
          python configure.py ${{ matrix.configuration }} 
      - name: Configure FFmpeg
        shell: "bash"
        run: |
          export PATH="$(pwd)/vendor:$PATH"
          echo $PATH
          which yasm

          cd FFmpeg
          ls -la
          pwd

          ../run_configure.sh
      - name: Build FFmpeg
        shell: msys2 {0}
        run: |
          export PATH="$(pwd)/vendor:$PATH"
          echo $PATH
          which yasm

          cd FFmpeg
          ls -la
          pwd

          echo "Removing link as it might conflict"
          rm -Rf /usr/bin/link

          echo "Compiling"
          /usr/bin/make -j4

          echo "Installing"
          /usr/bin/make install
      - name: Package libraries
        run: |
          $configuration = "${{ matrix.configuration }}"
          $zipName = "${configuration}_sharedlibs_x86_64-pc-windows-msvc.zip"
          echo "Creating zip $zipName"
          Compress-Archive -Path "FFmpeg/SHARED_LIBS" -DestinationPath $zipName

          ls

          # Pass zip name to next step
          echo "{zipName}={$zipName}" >> $GITHUB_OUTPUT
      - name: "Publish as release"
        uses: softprops/action-gh-release@v2
        with:
          files: "*msvc.zip"
          tag_name: "build"
          draft: false
          prerelease: false
      # - name: Setup tmate session
      #   if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3
